// Generated by CoffeeScript 1.4.0
(function() {
  var GmetricWrapper, gmetricsrv,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  gmetricsrv = require('gmetric');

  /**
   * Gmetric wrapper
  */


  GmetricWrapper = (function() {

    function GmetricWrapper(interval) {
      this.interval = interval;
      this.stop_gmond = __bind(this.stop_gmond, this);
      this.setup_gmond = __bind(this.setup_gmond, this);
      this.value_type = __bind(this.value_type, this);
      this.slope = __bind(this.slope, this);
      this.valid_counter_types = ['gauge, counter, derive, absolute'];
      this.gmetric = null;
      this.gmond_interval_id = null;
    }

    /**
     * Returns the integer lookup for the given slope type for gmetric.
     * @param {String} (name) The name of the slope type
     * @return {Integer} The integer representation of the name lookup
    */


    GmetricWrapper.prototype.slope = function(name) {
      var value_lookup;
      value_lookup = {
        '0': "zero",
        none: "zero",
        zero: "zero",
        positive: "positive",
        '1': "positive",
        negative: "negative",
        '-1': "negative",
        both: "both"
      };
      name = value_lookup[name.toString().toLowerCase()];
      if (name === void 0) {
        name = "unspecified";
      }
      return gmetricsrv["SLOPE_" + (name.toUpperCase())];
    };

    /**
     * Returns the integer lookup for the given data type for gmetric.
     * @param {String} (name) The name of the data type
     * @return {Integer} The integer representation of the name lookup
    */


    GmetricWrapper.prototype.value_type = function(name) {
      var value_lookup;
      value_lookup = {
        string: "string",
        ushrt: "unsigned_short",
        ushort: "unsigned_short",
        unsigned_short: "unsigned_short",
        uint16: "unsigned_short",
        short: "short",
        shrt: "short",
        int16: "short",
        uint: "unsigned_int",
        uint32: "unsigned_int",
        int: "int",
        int32: "int",
        float: "float",
        double: "double"
      };
      name = value_lookup[name.toString().toLowerCase()];
      if (name === void 0) {
        name = "unknown";
      }
      return gmetricsrv["VALUE_" + (name.toUpperCase())];
    };

    /**
     * Sets up the gmond metric spooler.
     * @param {String} (host) The target gmond host
     * @param {String} (port) The target gmond port
     * @param {String} (spoof) The spoofed hostname to act as
    */


    GmetricWrapper.prototype.setup_gmond = function(host, port, spoof) {
      var _this = this;
      this.gmetric = new gmetricsrv();
      this.gmetric.gmetric(host, port, spoof);
      if (!this.interval) {
        return;
      }
      return this.gmond_interval_id = setInterval(function() {
        if (_this.gmetric) {
          return _this.gmetric.sendMetric();
        }
      }, this.interval);
    };

    /**
     * Stops the gmond metric spooler.
    */


    GmetricWrapper.prototype.stop_gmond = function() {
      if (this.gmond_interval_id) {
        return clearInterval(this.gmond_interval_id);
      }
    };

    return GmetricWrapper;

  })();

  module.exports = GmetricWrapper;

}).call(this);
